=== frest0512/Tasks/src/main/webapp/META-INF/restriction/restriction.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="security">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="constraint" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="url-pattern" type="xs:string"/>
                            <xs:element name="role" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="admin"/>
                                        <xs:enumeration value="user"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== frest0512/Tasks/src/main/webapp/META-INF/restriction/restriction.xml
<?xml version="1.0"?>
<security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="restriction.xsd">
    <constraint>
        <url-pattern>/admin/*</url-pattern>
        <role>admin</role >
    </constraint>
    <constraint>
        <url-pattern>/user/*</url-pattern>
        <role>user</role >
    </constraint>
    <constraint>
        <url-pattern>/order</url-pattern>
        <role>user</role >
    </constraint>
</security>
